spring.application.name=party-management

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/PARTY_MGM_05162026-0140

# Database username
spring.datasource.username=admin

# Database password
spring.datasource.password=admin

# Postgres Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auto table creation (use carefully)
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# Auto Compile
spring.devtools.restart.enabled=true

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html


# Show all endpoints including actuator (optional)
springdoc.show-actuator=false

# Sort endpoints alphabetically (optional)
springdoc.swagger-ui.operationsSorter=alpha


